### ISSUE TITLE
mml再生の表示の不具合のご報告

### ISSUE THREAD

**Issue by kojix2** [YoshihiroOgura/RBoardDocument#1]
こんにちは。

https://yoshihiroogura.github.io/RBoardDocument/pwm.html
Rboardの公式ページの、PWMのサンプルのページの、「mml再生」が正しく表示されていないことに気が付きました。

![image](https://user-images.githubusercontent.com/5798442/108805906-8e475e80-75e3-11eb-8387-c960c0dc5417.png)

中略

![image](https://user-images.githubusercontent.com/5798442/108805918-9acbb700-75e3-11eb-8b72-25c457074f62.png)

修正いただけると幸いです。

**Comment by YoshihiroOgura** [comment]
ご報告ありがとうございます。修正いたしましたm(_ _"m)
